language: rust
rust: stable
sudo: false
script:
  - cargo test
notifications:
  email: false
  irc:
    channels:
      - "ircs://irc.pdgn.co:6697/#commits"
    template:
      - "%{repository_slug}/%{branch} (%{commit} - %{author}): %{message}"
    skip_join: true
